# Site settings
title: Digital Logic Design
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Minho Kim
user_description: I'm with South Korea's major college student media software. Learn programming, broadcasting, and acoustics. And I am very interested in drawing pictures. I have made phone books, video management programs, and other works can be found at the following address. <a href= "https://twitter.com/Erbe88076451"> Twitter</a>
user_title: Student. Kangwon Univ.
email: rlaalsgh0511@naver.com
# twitter_username: Erbe
# github_username:  minho0511
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
